\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Calorie Consumption During Bicycle Work: A Statistical Analysis of an Incomplete Dataset},
            pdfauthor={Nuno Chicoria (r0698632), Boris Shilov (r0686052), Murat Cem Kose (r0689792), Yibing Liu (r0684580), Robin Vermote (r0482826)},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{Calorie Consumption During Bicycle Work: A Statistical Analysis of an
Incomplete Dataset}
  \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \author{Nuno Chicoria (r0698632), Boris Shilov (r0686052), Murat Cem Kose
(r0689792), Yibing Liu (r0684580), Robin Vermote (r0482826)}
  \preauthor{\centering\large\emph}
  \postauthor{\par}
  \predate{\centering\large\emph}
  \postdate{\par}
  \date{23 Mart, 2018}


\usepackage{amsthm}
\newtheorem{theorem}{Theorem}[section]
\newtheorem{lemma}{Lemma}[section]
\theoremstyle{definition}
\newtheorem{definition}{Definition}[section]
\newtheorem{corollary}{Corollary}[section]
\newtheorem{proposition}{Proposition}[section]
\theoremstyle{definition}
\newtheorem{example}{Example}[section]
\theoremstyle{definition}
\newtheorem{exercise}{Exercise}[section]
\theoremstyle{remark}
\newtheorem*{remark}{Remark}
\newtheorem*{solution}{Solution}
\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{Introduction}\label{introduction}

This project aimed to examine data originally gathered by Macdonald
(1914) and conveyed to us by Greenwood and TF (1918), consisting of
observations on seven people performing work using a bicycle ergometer,
although our current dataset appears to include extra values and data
not found in Greenwood and TF (1918), though these values may indeed be
present in Macdonald (1914), access to which could not be obtained in a
timely manner. In the body of this work it shall be assumed that every
row in our dataset represents a separate individual, giving a total of
24 separate individuals across 24 rows. The dataset includes three
separate measurements - weight of the individuals, calories per hour
spent by individuals which serves as a measure of workout intensity, and
calories spent during the task.

\begin{verbatim}
##    weight calhour calories
## 1    43.7    19.0       NA
## 2    43.7    43.0      279
## 3    43.7    56.0      346
## 4    54.6    13.0       NA
## 5    54.6    19.0       NA
## 6    54.6    43.0      280
## 7    54.6    56.0      335
## 8    55.7    13.0       NA
## 9    55.7    26.0      212
## 10   55.7    34.5      244
## 11   55.7    43.0      285
## 12   58.8    13.0       NA
## 13   58.8    43.0      298
## 14   60.5    19.0       NA
## 15   60.5    43.0      317
## 16   60.5    56.0      347
## 17   61.9    13.0       NA
## 18   61.9    19.0      216
## 19   61.9    34.5      265
## 20   61.9    43.0      306
## 21   61.9    56.0      348
## 22   66.7    13.0       NA
## 23   66.7    43.0      324
## 24   66.7    56.0      352
\end{verbatim}

\section{Methods and Results}\label{methods-and-results}

\subsection{Data exploration}\label{data-exploration}

A set of summary statistics for the dataset is presented below. It can
be immediately seen that the response calories variable is missing in
eight cases and is the only incomplete variable in the dataset. The mean
and median values for all variables in the dataset are very similar to
each other which indicates a symmetric distribution. A matrix of summary
plots for the dataset is presented in Figure \ref{fig:PairsPlot}. We can
clearly see what appears to be an extremely strong positive correlation
between calories and workout intensity (\(0.95\)), and a very small
positive correlation between calories and weight(\(0.11\)). The
scatterplot further indicates that the correlation between calories and
workout intensity is very likely to be linear.

The distributions of the values are plotted as boxplots in Fig.
\ref{fig:muscledataboxplots}. Note that the response variable is plotted
with missing values excluded in all of these figures, thus despite
expecting an approximately similar distribution between workout
intensity and calories variables, the calories distribution is shifted
upwards due to the missing values.

\begin{verbatim}
##                 weight  calhour  calories
## nbr.val        24.0000  24.0000   16.0000
## nbr.null        0.0000   0.0000    0.0000
## nbr.na          0.0000   0.0000    8.0000
## min            43.7000  13.0000  212.0000
## max            66.7000  56.0000  352.0000
## range          23.0000  43.0000  140.0000
## sum          1381.0000 817.0000 4754.0000
## median         58.8000  38.7500  302.0000
## mean           57.5417  34.0417  297.1250
## SE.mean         1.3453   3.3396   11.4669
## CI.mean.0.95    2.7829   6.9085   24.4412
## var            43.4338 267.6721 2103.8500
## std.dev         6.5904  16.3607   45.8677
## coef.var        0.1145   0.4806    0.1544
\end{verbatim}

\begin{figure}[htbp]
\centering
\includegraphics{Final_Report_files/figure-latex/figBoxPlots-1.pdf}
\caption{\label{fig:figBoxPlots}\label{fig:muscledataboxplots}Boxplots for
the dependent variables weight, calhour and independent variable
calories.}
\end{figure}

\begin{figure}[htbp]
\centering
\includegraphics{Final_Report_files/figure-latex/figPairsPlot-1.pdf}
\caption{\label{fig:figPairsPlot}\label{fig:PairsPlot}A summary statistics
plot of the dataset using the ggplot command.}
\end{figure}

We check the signifance of the two positive correlations we have found
using Pearson's correlation (using Central Limit Theorem as the dataset
contains around 20 rows). Here \(H_0:correlation=0\);
\(H1:correlation \neq 0;\) \(95\%CI\).

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  muscledata_edit$calhour and muscledata_edit$calories
## t = 12, df = 14, p-value = 2e-08
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.8615 0.9832
## sample estimates:
##    cor 
## 0.9511
\end{verbatim}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  muscledata_edit$weight and muscledata_edit$calories
## t = 0.42, df = 14, p-value = 0.7
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.4068  0.5753
## sample estimates:
##    cor 
## 0.1114
\end{verbatim}

Clearly we reject the null hypothesis with regards to workout intensity
and calories and accept it with regards to weight and calories. This
indicates that there is a non-spurious correlation between workout
intensity and calories in the population.

\subsection{Missing data exploration}\label{missing-data-exploration}

\begin{figure}[htbp]
\centering
\includegraphics{Final_Report_files/figure-latex/figMissDatBox-1.pdf}
\caption{\label{fig:figMissDatBox}\label{fig:MissDatBox}Patterns of missing
data across variables.}
\end{figure}

A histogram of missing data is shown in Fig. \ref{fig:MissDatBox}. We
confirm our previous observation that all the missing values are located
in our response variable.

Fig. \ref{fig:MissingHists}A and C we see that the missing data
approximately evenly distributed among the different weight variables.
In Fig. \ref{fig:MissingHists}B and D we see that the missing data
distribution is extremely biased towards the lower end of the range with
regards to workout intensity. This may be because of the difficulty in
measuring heat production at lower exercise intensity - in other words,
the missingness is likely systematic due to technical noise.
Importantly, the missingness appears to depend only on an observed
variable in this study - the calories. Thus, this suggests
``Missing-at-Random'' as the most probable missing data mechanism,
allowing us to proceed with applying missing data strategies -
particularly MI and IPW. We will nonetheless evaluate some of the more
common methods as well.

\begin{figure}[htbp]
\centering
\includegraphics{Final_Report_files/figure-latex/figMissingHists-1.pdf}
\caption{\label{fig:figMissingHists}\label{fig:MissingHists}Histograms of
the observed and missing data as well as marginplots depicting
histograms and correlations.}
\end{figure}

\subsection{Complete case analysis}\label{complete-case-analysis}

Complete case analysis relies on removing rows of our dataset that have
missing values - giving us a restricted sample of 16 rows to work with.

We select the best linear model to use for complete case analysis using
stepwise Akaike's Information Criterion - a measure of the quality of
our statistical models relative to each other, which indicates the
amount of information lost by excluding or including model terms.

\begin{verbatim}
## Start:  AIC=123.4
## calories ~ 1
## 
##           Df Sum of Sq   RSS   AIC
## + calhour  1     28544  3014  87.8
## <none>                 31558 123.4
## + weight   1       392 31166 125.2
## 
## Step:  AIC=87.81
## calories ~ calhour
## 
##           Df Sum of Sq   RSS   AIC
## + weight   1      1234  1780  81.4
## <none>                  3014  87.8
## - calhour  1     28544 31558 123.4
## 
## Step:  AIC=81.39
## calories ~ calhour + weight
## 
##                  Df Sum of Sq   RSS   AIC
## + weight:calhour  1       782   998  74.1
## <none>                         1780  81.4
## - weight          1      1234  3014  87.8
## - calhour         1     29386 31166 125.2
## 
## Step:  AIC=74.13
## calories ~ calhour + weight + calhour:weight
## 
##                  Df Sum of Sq  RSS  AIC
## <none>                         998 74.1
## - calhour:weight  1       782 1780 81.4
\end{verbatim}

Lower AIC is better, thus we conclude that a model incorporating weight,
calhour and an interaction term is the most explanatory linear model
available given our exploratory analysis. In mathematical terms: \[
calories_i = \beta_0 + \beta_1*weight_i + \beta_2*calhour_i + \beta_3*(weight_i*calhour_i) + \epsilon_i
\]

The summary for this model:

\begin{verbatim}
## 
## Call:
## lm(formula = calories ~ weight + calhour + weight * calhour, 
##     data = muscledata_edit)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -12.48  -5.70  -1.04   2.39  16.95 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(>|t|)    
## (Intercept)    -330.884    124.674   -2.65  0.02102 *  
## weight            7.728      2.106    3.67  0.00321 ** 
## calhour          11.787      2.548    4.63  0.00058 ***
## weight:calhour   -0.132      0.043   -3.07  0.00977 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 9.12 on 12 degrees of freedom
## Multiple R-squared:  0.968,  Adjusted R-squared:  0.96 
## F-statistic:  123 on 3 and 12 DF,  p-value: 2.89e-09
\end{verbatim}

All four terms appear highly significant in this model. However, the
intercept term \(\beta_0\) does not have a physical meaning in this
model. The significance of the interaction term means that the weight
has an influence on the effect of workout intensity on calories.

An effects plot is presented in Fig. \ref{fig:AllEffGoodModel}. This
plot indicates that there is a decrease in slope, determined by workout
intensity and calories, as workout intensity is increasing.

\begin{figure}[htbp]
\centering
\includegraphics{Final_Report_files/figure-latex/figAllEffGoodModel-1.pdf}
\caption{\label{fig:figAllEffGoodModel}\label{fig:AllEffGoodModel}The All
Effects plot for the Complete Case linear model.}
\end{figure}

\subsection{Multiple imputation
analysis}\label{multiple-imputation-analysis}

Multiple imputation is an approach to deal with incomplete data that can
be applied to univariate or multivariate data. The technique replaces
missing values with two or more imputed values. Unlike simpler single
imputation methods where only a single value is imputed, such as mean
imputation, multiple imputation as the name suggests replaces each
missing value with multiple imputed values, in effect generating a
number of datasets. Practically, this allows us to represent a variety
of theoretical mechanisms for why the nonresponse occured. These
differing datasets are known as multiply imputed datasets. These
datasets are used to generate a matrix of regression coefficients, in
essence building a regression model. We generate as many regression
coefficient matrices as there are multiply imputed datasets. We then
pool the regression coefficients into a single estimate which can be
used to estimate variance (Rubin 2004). There are several methods of
imputation available.

First we use the predictive mean matching (PMM) method. This is one of
the ``default'' methods and it faithfully reproduces the relations
present in the original data even if they happen to be nonlinear. The
results of such a simulation with 100 imputed value datasets:

According to the resulting PMM model, none of the possible dependent
variables have any statistically significant influence on our response
variable. The effects plot in Fig \ref{fig:AllEffGoodModel} shows that
there is no influence of the interaction term on the response variable
since the slope does not change. Notice also the contraction of the
\(95\%\) confidence limit due to the imputation process.

The strip plot is shown in Fig. \ref{fig:StripCompPMM} showing original
data in pink and generated data in purple. We thus indeed confirm
PMM-generated data follows very similar relations to the original
dataset.

\begin{figure}[htbp]
\centering
\includegraphics{Final_Report_files/figure-latex/figAllEffCompPMM-1.pdf}
\caption{\label{fig:figAllEffCompPMM}\label{fig:AllEffGoodModel}The All
Effects plot for MI using the PMM method.}
\end{figure}

\begin{figure}[htbp]
\centering
\includegraphics{Final_Report_files/figure-latex/figStripCompPMM-1.pdf}
\caption{\label{fig:figStripCompPMM}\label{fig:StripCompPMM}The strip plot
of PMM data.}
\end{figure}

An alternative to PMM with our dataset is Bayesian linear regression,
which can create univariate missing data. This reformulates our linear
model in probabilistic terms. In this method we assume a prior
distribution for the parameters of the regression (Rubin 2004). In our
method the prior distribution is assumed to be normal (the normal
model). The result is:

\begin{verbatim}
##                     est       se        t    df Pr(>|t|)      lo 95
## (Intercept)    -4.51317 86.98705 -0.05188 7.142  0.96004 -209.38023
## weight          2.20493  1.46094  1.50926 7.468  0.17232   -1.20623
## calhour         5.30120  1.89356  2.79960 8.917  0.02091    1.01159
## weight:calhour -0.02234  0.03189 -0.70053 9.269  0.50080   -0.09416
##                    hi 95 nmis    fmi lambda
## (Intercept)    200.35389   NA 0.6777 0.5985
## weight           5.61609    0 0.6605 0.5804
## calhour          9.59081    0 0.5843 0.5004
## weight:calhour   0.04948   NA 0.5658 0.4812
\end{verbatim}

According to our Bayesian model, the workout intensity is the only
variable that has a statistically significant influence on our response
variable. The effects plot in Fig. \ref{fig:AllEffCompNORM} demonstrates
a similar finding to the PMM effects plot in that due to preserving the
slope remaining the same the interaction variable clearly does not have
much effect. The strip plot in Fig. \ref{fig:StripCompNORM} highlights
the probabilistic nature of the Bayesian imputation algorithm, the
imputed data points being sampled from the obtained posterior
distribution of our parameters.

\begin{figure}[htbp]
\centering
\includegraphics{Final_Report_files/figure-latex/figAllEffCompNORM-1.pdf}
\caption{\label{fig:figAllEffCompNORM}\label{fig:AllEffCompNORM}The All
Effects plot for MI using the Bayesian NORM method.}
\end{figure}

\begin{figure}[htbp]
\centering
\includegraphics{Final_Report_files/figure-latex/figStripCompNORM-1.pdf}
\caption{\label{fig:figStripCompNORM}\label{fig:StripCompNORM}The strip plot
of Bayesian NORM data.}
\end{figure}

\subsection{Inverse Probability Weighting
analysis}\label{inverse-probability-weighting-analysis}

The Inverse Probability Weighting method attemps to mitigate the bias
introduced by complete case studies if the excluded population appears
to be systematically different from the complete cases. The complete
cases are weighted using the inverse probability of their being a
complete case. As you may recall, this is intuitively a very plausible
model for our data since a mechanistic hypothesis for the MAR present is
due to technical noise. To emphasize, in IPW the analytical model is
only fitted to complete cases (Seaman and White 2013). The results are
thus:

\begin{verbatim}
## Warning: In lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) :
##  extra argument 'family' will be disregarded
\end{verbatim}

\begin{verbatim}
## 
## Call:
## lm(formula = calories ~ weight + calhour + weight * calhour, 
##     data = IPWanal_muscledata, weights = muscledata$w)
## 
## Weighted Residuals:
##    Min     1Q Median     3Q    Max 
##  -91.0  -40.5  -11.0   20.1  129.8 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(>|t|)    
## (Intercept)    -353.7928   129.1577   -2.74  0.01796 *  
## weight            8.1131     2.1698    3.74  0.00283 ** 
## calhour          12.1321     2.6513    4.58  0.00064 ***
## weight:calhour   -0.1378     0.0445   -3.10  0.00926 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 68.2 on 12 degrees of freedom
##   (8 observations deleted due to missingness)
## Multiple R-squared:  0.97,   Adjusted R-squared:  0.962 
## F-statistic:  128 on 3 and 12 DF,  p-value: 2.25e-09
\end{verbatim}

All the parameters are highly significant, similarly to the complete
cases analysis as can be expected. Fig. \ref{fig:AllEffIPW} effects plot
is also highly similar.

\begin{figure}[htbp]
\centering
\includegraphics{Final_Report_files/figure-latex/figAllEffIPW-1.pdf}
\caption{\label{fig:figAllEffIPW}\label{fig:AllEffIPW}The All Effects plot
for our IPW-modelled data.}
\end{figure}

The relative AIC values of the complete case and IPW models can be used
for comparison to validate that our IPW model is indeed better than
simple CC:

\begin{verbatim}
## [1] 121.5
\end{verbatim}

\begin{verbatim}
## [1] 121.1
\end{verbatim}

We can observed that IPW yields only a miniscule improvement over CC in
this case.

\section{Discussion}\label{discussion}

Due to the NA values, we conducted a full model analysis with a complete
case and two different methods for NA values replacement (MI and IPW).
Because the NA values are not evenly distributed among workout
intensity, we decided to try different approaches for NA handling.

\begin{figure}[htbp]
\centering
\includegraphics{Final_Report_files/figure-latex/figDiscCompare-1.pdf}
\caption{\label{fig:figDiscCompare}\label{fig:DiscCompare}Condensed All
Effects plots from the various analysis types side by side.}
\end{figure}

\begin{figure}[htbp]
\centering
\includegraphics{Final_Report_files/figure-latex/figDiscInteraction-1.pdf}
\caption{\label{fig:figDiscInteraction}\label{fig:DiscInteraction}Interaction
scatterplots for the normal NA-excluded dataset, values fitted using
NORM and values fitted using PMM.}
\end{figure}

At Fig. \ref{fig:DiscCompare} we are comparing the 4 effect plots
previously shown. In our MI models, there are no significant changes in
the slope which means that the interaction factor plays no role over the
weight and calories as we change the workout intensity values. This
supports the p-value we observed while building the model that showed us
no significance for the interaction term. Nevertheless, to be able to
compare all our models, and since the MI models with less parameters
showed no overall improvement, we decided to use the same parameters to
generate all models. For both the Complete Case and IPW model we can
observe a change in the slope for higher values of workout intensity.
This leads us to conclude that the interaction term is significant for
this models as shown by their respective p-values.

In the following three plots in Fig. \ref{fig:DiscInteraction} we can
see that the behaviour of the interaction factor vs.~calories is
somewhat simillar for the CC model and the two models created under MI.
These three graphs are relevant to see how the two different methods
chose in MI generate the new values. We can see in the graph for the PMM
method that the line deviates more from the original data than in the
Bayesian NORM graph. So, the PMM method of generating new values
actually appears to be bringing our model away from the original data.

Finally, IPW assigns weights to each available observation. In our case,
all calories values corresponding to workout intensity 13 are missing.
Hence, the method cannot assign a weight to values that do not exist.
So, the only difference between the CC and IPW model is based on value
generated for the workout intensity 19 (the only other entry with a
missing value). This supports all our previous graphs coefficient values
for both models that are always simmilar.

\section{Conclusion}\label{conclusion}

Based on our discussion, and since the IPW model presented a lower AIC
value than the CC model, we chose as a final model the IPW one.

\[
calories_i = $-353.7928$  + $8.1131$*weight_i + $12.1321$*calhour_i - $-0.1378$*(weight_i*calhour_i) + \epsilon_i
\]

Analysing the model we conclude that both weight and workout intensity
have a positive impact in the heat production for the individual. On the
other hand, the interaction term has a slight negative impact in the
heat production that is shown in previous graphs when we start to arrive
at a plateau for higher values of workout intensity for variable
weights. Also of importance is the intercept value \(-351.223\) that has
no physical significance as heat production is a strictly positive
value.

\begin{verbatim}
##                    2.5 %    97.5 %
## (Intercept)    -635.2033 -72.38233
## weight            3.3855  12.84065
## calhour           6.3555  17.90875
## weight:calhour   -0.2347  -0.04081
\end{verbatim}

Looking at the confidence intervals, we affirm with a 95\% confidence
that our values will fall inside the presented intervals. Hence, weight
and workout intensity will be positive and the interaction factor
negative. This is a good parameter to estimate how the population falls
under our model.

\section*{References}\label{references}
\addcontentsline{toc}{section}{References}

\hypertarget{refs}{}
\hypertarget{ref-greenwood1918efficiency}{}
Greenwood, M, and Captain RAMC TF. 1918. ``On the Efficiency of Muscular
Work.'' \emph{Proc. R. Soc. Lond. B} 90 (627). The Royal Society:
199--214.

\hypertarget{ref-macdonald1914mechanical}{}
Macdonald, JS. 1914. ``The Mechanical Efficiency of Man.'' \emph{Proc.
Phys. Soc. in Journ. of Physiol} 48.

\hypertarget{ref-rubin2004multiple}{}
Rubin, Donald B. 2004. \emph{Multiple Imputation for Nonresponse in
Surveys}. Vol. 81. John Wiley \& Sons.

\hypertarget{ref-seaman2013review}{}
Seaman, Shaun R, and Ian R White. 2013. ``Review of Inverse Probability
Weighting for Dealing with Missing Data.'' \emph{Statistical Methods in
Medical Research} 22 (3). Sage Publications Sage UK: London, England:
278--95.


\end{document}
